#!/bin/bash

# Start message
echo "Starting."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Confirmation to overwrite existing files
# echo "This may overwrite existing files in your home directory."
# echo ""
# echo "Do you want to continue? (Y/n)"
# read -r -n 1
# if [[ $REPLY =~ ^[Nn]$ ]]; then
#     exit 1
# fi

# Copy files to ~
rsync --exclude=".DS_Store" \
    --exclude="Icon?" \
    --exclude="setup" \
    --exclude=".gitconfig" \
    -avh \
    --progress \
    . ~;

# Global git ignore
git config --global core.excludesfile '~/.gitignore'

# Finish message
echo "Completed."
echo ""
echo "You may need to restart your terminal programs."
